### ISSUE TITLE
Not working on my home PC!

### ISSUE THREAD

**Issue by ddm2112** [ebfret/ebfret-gui#1]
When I try to run the analysis on my home PC it doesn't work, though it doesn't give me an error message. After I load my traces, the "Run" button is disabled/grayed out, so I am unable to start the analysis. I am using Windows 7, and I downloaded the most recent version of the program today as well as the C++ compiler thing from http://www.microsoft.com/en-us/download/confirmation.aspx?id=14632

**Comment by jwvdm** [comment]
Many thanks. This is fixed in commit e9834ca1063a742e17492ae9acc28dd5f4cab268

Could you try again with the latest sources?
