### ISSUE TITLE
Option to make viterbi path come on and off

### ISSUE THREAD

**Issue by ddm2112** [ebfret/ebfret-gui#19]
vbFRET has a check box where you can toggle the viterbi path overlayed on the traces on and off. This is helpful for checking whether the model matches well with the raw data, since the raw data is sometimes covered up and obscured by the viterbi path. 
Also, I have found myself getting distracted by the viterbi paths on the middle/donor acceptor plots when quickly flipping through traces. It would be nice to have the option to turn these off so as to guide my sight towards the FRET traces, which is what I really want to look at post-analysis.

**Comment by jwvdm** [comment]
implemented in d48c0e4019cd785f2faf9621918afe425b270abf

**Comment by jinrang** [comment]
Hi JW,

I just have downloaded the newer version of ebFRET and am trying to use it now.

# One question that I have is that I can not save summary files or path data files any more (returns error message such as below).

One or more output arguments not assigned during call to
"ebfret.analysis.normalize".

Error in ebfret.analysis.hmm.report (line 57)
        rep(s).Statistics.Occupancy.Mean = ...

Error in ebfret.ui.MainWindow/export_summary (line 39)
    report = ebfret.analysis.hmm.report(...

Error in ebfret.ui.MainWindow/MainWindow/@(source,event)export_summary(self)

Error while evaluating uimenu Callback

# End of error message

I am also curious about what "Prior" and "Posterior" do, but I'll wait until next time.

Best,
Jin

```
Jinrang Kim, Ph.D
Laboratory of Ruben L. Gonzalez &
Laboratory of John F. Hunt
Columbia University
```

**Comment by jwvdm** [comment]
That error should be fixed now Jin -- thanks for reporting. Next time, could you start a new issue?

JW
