### ISSUE TITLE
A few things

### ISSUE THREAD

**Issue by ddm2112** [ebfret/ebfret-gui#2]
It would be nice if the graphs in the GUI had their axes labeled.
Also, can we have the option to save the viterbi paths as an output file? This might have three columns giving 1) the trace number, 2) idealized FRET value, and 3) the ID number for the state to which a given dwell has been assigned. This would be useful for downstream analysis/plotting.

**Comment by jwvdm** [comment]
Thanks! I opened two separate issues for this.
